language: csharp
sudo: required
dist: trusty
mono: none
dotnet: 1.0.0
addons:
  apt:
    packages:
    - gettext
    - libcurl4-openssl-dev
    - libicu-dev
    - libssl-dev
    - libunwind8
    - zlib1g
env:
  global:
    - DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true
    - DOTNET_CLI_TELEMETRY_OPTOUT: 1    
os:
  - linux
  - osx
osx_image: xcode7.3
install:
  - ./scripts/dotnet-install.sh
before_script:
  - dotnet restore
script:
  - dotnet build
  - dotnet test test/Orchard.Tests/Orchard.Tests.csproj